export default {
  options: [
    { label: "Peau abîmée", value: "Peau abîmée" },
    { label: "Peau sèche", value: "Peau sèche" },
    { label: "Peau irritée", value: "Peau irritée" },
    { label: "vergetures", value: "vergetures" },
    { label: "Crevasses", value: "Crevasses" },
    { label: "Gerçures", value: "Gerçures" },
    { label: "Petites coupures", value: "Petites coupures" },
    { label: "Eczéma", value: "Eczéma" },
    { label: "Acné", value: "Acné" },
    { label: "Verrue", value: "Verrue" },
    { label: "Diarrhée", value: "Diarrhée" },
    { label: "Gastro", value: "Gastro" },
    { label: "varices", value: "varices" },
    { label: "Rides", value: "Rides" },
    { label: "Stress", value: "Stress" },
    { label: "Rhume", value: "Rhume" },
    { label: "Bronchite", value: "Bronchite" },
    { label: "Antalgique", value: "Antalgique" },
    { label: "Antifongique", value: "Antifongique" },
    { label: "Anti-inflammatoire", value: "Anti-inflammatoire" },
    { label: "Anti-nauséeuse", value: "Anti-nauséeuse" },
    { label: "Antiseptique", value: "Antiseptique" },
    { label: "Antispasmodique", value: "Antispasmodique" },
    { label: "Antivirale", value: "Antivirale" },
    { label: "Carminative", value: "Carminative" },
    { label: "Décontractante", value: "Décontractante" },
    {
      label: "Tonique digestif et hépatique",
      value: "Tonique digestif et hépatique",
    },
    { label: "Équilibrante", value: "Équilibrante" },
    { label: "Expectorante", value: "Expectorante" },
    { label: "Antiparasitaire", value: "Antiparasitaire" },
    { label: "Immunostimulante", value: "Immunostimulante" },
    { label: "Analgésique douce", value: "Analgésique douce" },
    { label: "Analgésique", value: "Analgésique" },
    { label: "Antiprurigineuse", value: "Antiprurigineuse" },
    { label: "Bactéricide", value: "Bactéricide" },
    { label: "Cicatrisante", value: "Cicatrisante" },
    {
      label: "Stimulante respiratoire et cardiaque",
      value: "Stimulante respiratoire et cardiaque",
    },
    { label: "Anti-bactérienne", value: "Anti-bactérienne" },
    { label: "Stimulante digestive", value: "Stimulante digestive" },
    {
      label: "Stimulante du système immunitaire",
      value: "Stimulante du système immunitaire",
    },
    {
      label: "Tonifiante du système nerveux",
      value: "Tonifiante du système nerveux",
    },
    { label: "Vermifuge", value: "Vermifuge" },
    { label: "Verrucide", value: "Verrucide" },
    { label: "Anticoagulante", value: "Anticoagulante" },
    { label: "Hypertensive", value: "Hypertensive" },
    { label: "Hypocholestérolémiante", value: "Hypocholestérolémiante" },
    { label: "Stimulante circulatoire", value: "Stimulante circulatoire" },
    { label: "Antihémorragique", value: "Antihémorragique" },
    { label: "Neurotonique", value: "Neurotonique" },
    { label: "Stimulante veineuse", value: "Stimulante veineuse" },
    {
      label: "Calculs biliaires et rénaux",
      value: "Calculs biliaires et rénaux",
    },
    { label: "Drainante", value: "Drainante" },
    { label: "Fluidifiante sanguine", value: "Fluidifiante sanguine" },
    { label: "Mange-graisses", value: "Mange-graisses" },
    { label: "Nausées de la grossesse", value: "Nausées de la grossesse" },
    { label: "Stimulante immunitaire", value: "Stimulante immunitaire" },
    { label: "Régulatrice métabolique", value: "Régulatrice métabolique" },
    { label: "Décongestionnante nasale", value: "Décongestionnante nasale" },
    { label: "Immunomodulante", value: "Immunomodulante" },
    { label: "Mucolytique", value: "Mucolytique" },
    { label: "Respiratoire", value: "Respiratoire" },
    { label: "Antidouleur articulaire", value: "Antidouleur articulaire" },
    { label: "Antidouleur musculaire", value: "Antidouleur musculaire" },
    { label: "Stimulante du foie", value: "Stimulante du foie" },
    {
      label: "Stimulante du système digestif",
      value: "Stimulante du système digestif",
    },
    { label: "Anti-hématome", value: "Anti-hématome" },
    {
      label: "Antiphlébitique (prévention)",
      value: "Antiphlébitique (prévention)",
    },
    {
      label: "Antispasmodique vasculaire",
      value: "Antispasmodique vasculaire",
    },
    {
      label: "Régulatrice du système nerveux",
      value: "Régulatrice du système nerveux",
    },
    {
      label: "Apaisante du système nerveux",
      value: "Apaisante du système nerveux",
    },
    { label: "Cicatrisante cutanée", value: "Cicatrisante cutanée" },
    { label: "Décontractante musculaire", value: "Décontractante musculaire" },
    { label: "Antitoxique", value: "Antitoxique" },
    { label: "Anti-poux", value: "Anti-poux" },
    {
      label: "Dermatoses infectieuses, cicatricielles, escarres",
      value: "Dermatoses infectieuses, cicatricielles, escarres",
    },
    { label: "Stimulante hépatique", value: "Stimulante hépatique" },
    { label: "Vasodilatatrice", value: "Vasodilatatrice" },
    {
      label: "Stimulante veineuse et lymphatique",
      value: "Stimulante veineuse et lymphatique",
    },
    { label: "Détoxifiante", value: "Détoxifiante" },
    { label: "Diurétique", value: "Diurétique" },
    {
      label: "Drainante du foie et des reins",
      value: "Drainante du foie et des reins",
    },
    { label: "Hypotensive", value: "Hypotensive" },
    { label: "Lipolytique", value: "Lipolytique" },
    { label: "Calmante nerveuse", value: "Calmante nerveuse" },
    { label: "Tonique digestive", value: "Tonique digestive" },
    { label: "Antinauséeuse", value: "Antinauséeuse" },
    { label: "Rafraîchissante", value: "Rafraîchissante" },
    { label: "Régulatrice hépatique", value: "Régulatrice hépatique" },
    { label: "Stimulante cardiaque", value: "Stimulante cardiaque" },
    { label: "Stimulante pancréatique", value: "Stimulante pancréatique" },
    { label: "Anticatarrhale", value: "Anticatarrhale" },
    { label: "Fongicide", value: "Fongicide" },
    { label: "Tonique sexuelle", value: "Tonique sexuelle" },
    {
      label: "Anti-inflammatoire cutanée",
      value: "Anti-inflammatoire cutanée",
    },
    {
      label: "Décongestionnante lymphatique",
      value: "Décongestionnante lymphatique",
    },
    {
      label: "Décongestionnante veineuse",
      value: "Décongestionnante veineuse",
    },
    { label: "Tonique lymphatique", value: "Tonique lymphatique" },
    { label: "Tonique veineuse", value: "Tonique veineuse" },
    { label: "Antidouleur", value: "Antidouleur" },
    { label: "Anticellulite", value: "Anticellulite" },
    { label: "Circulatoire", value: "Circulatoire" },
    { label: "Tonifiante circulatoire", value: "Tonifiante circulatoire" },
    { label: "Anticatharrale", value: "Anticatharrale" },
    {
      label: "Apaisante pour le système nerveux",
      value: "Apaisante pour le système nerveux",
    },
    { label: "Mycoses", value: "Mycoses" },
    { label: "Régulatrice cutanée", value: "Régulatrice cutanée" },
    {
      label: "Régulatrice de la circulation sanguine",
      value: "Régulatrice de la circulation sanguine",
    },
    {
      label: "Régulatrice des cycles menstruels (oestrogénique)",
      value: "Régulatrice des cycles menstruels (oestrogénique)",
    },
    {
      label: "Stimulante hépatique (cholestérol)",
      value: "Stimulante hépatique (cholestérol)",
    },
    { label: "Radioprotectrice", value: "Radioprotectrice" },
    { label: "Tonique cardiaque", value: "Tonique cardiaque" },
    { label: "Calmante cardiaque", value: "Calmante cardiaque" },
    { label: "Tonique capillaire", value: "Tonique capillaire" },
    { label: "Antidémangeaison", value: "Antidémangeaison" },
    { label: "Anti-hémorragique", value: "Anti-hémorragique" },
    { label: "Antihypertensive", value: "Antihypertensive" },
    {
      label: "Antiparasitaire intestinale",
      value: "Antiparasitaire intestinale",
    },
    { label: "Cholestérol", value: "Cholestérol" },
    {
      label: "Rééquilibrante glandulaire",
      value: "Rééquilibrante glandulaire",
    },
    { label: "Aphrodisiaque", value: "Aphrodisiaque" },
    { label: "Cholagogue", value: "Cholagogue" },
    { label: "Cholérétique", value: "Cholérétique" },
    { label: "Facilite la digestion", value: "Facilite la digestion" },
    { label: "Stimulante lymphatique", value: "Stimulante lymphatique" },
    { label: "Régénérante cutanée", value: "Régénérante cutanée" },
    { label: "Tonique cutanée", value: "Tonique cutanée" },
    { label: "Antirhumatismale", value: "Antirhumatismale" },
    { label: "Protectrice cutanée", value: "Protectrice cutanée" },
    { label: "Fluidifiante du sang", value: "Fluidifiante du sang" },
    { label: "fongicide et parasiticide", value: "fongicide et parasiticide" },
    { label: "Antivomitive", value: "Antivomitive" },
    { label: "Digestive", value: "Digestive" },
    { label: "Lypolitique", value: "Lypolitique" },
    { label: "Antiseptique urinaire", value: "Antiseptique urinaire" },
    { label: "Détoxifiante hépatique", value: "Détoxifiante hépatique" },
    { label: "Eupeptique", value: "Eupeptique" },
    { label: "Protectrice du foie", value: "Protectrice du foie" },
    { label: "Anticellulitique", value: "Anticellulitique" },
    { label: "Antiradicalaire", value: "Antiradicalaire" },
    { label: "Dépurative", value: "Dépurative" },
    { label: "Raffermissante", value: "Raffermissante" },
    { label: "Régénérante", value: "Régénérante" },
    { label: "Répulsive des insectes", value: "Répulsive des insectes" },
    { label: "Tonique carminative", value: "Tonique carminative" },
    { label: "Stimulante de l'immunité", value: "Stimulante de l'immunité" },
    {
      label: "Stimulante digestive et intestinale",
      value: "Stimulante digestive et intestinale",
    },
    { label: "Stimulante respiratoire", value: "Stimulante respiratoire" },
    {
      label: "Stimulante de la circulation sanguine",
      value: "Stimulante de la circulation sanguine",
    },
    { label: "Emménagogue", value: "Emménagogue" },
    { label: "Antioxydante cutanée", value: "Antioxydante cutanée" },
    { label: "Stimulante biliaire", value: "Stimulante biliaire" },
    { label: "Antitussive", value: "Antitussive" },
    {
      label: "Décongestionnante bronchique",
      value: "Décongestionnante bronchique",
    },
    { label: "Fluidifiante bronchique", value: "Fluidifiante bronchique" },
    { label: "Adoucissante cutanée", value: "Adoucissante cutanée" },
    { label: "Calmante cutanée", value: "Calmante cutanée" },
    { label: "Desclérosante", value: "Desclérosante" },
    { label: "Relaxante", value: "Relaxante" },
    { label: "Antiallergique", value: "Antiallergique" },
    {
      label: "Antispasmodique neuromusculaire",
      value: "Antispasmodique neuromusculaire",
    },
    {
      label: "Anti-inflammatoire musculaire , articulaire",
      value: "Anti-inflammatoire musculaire , articulaire",
    },
    {
      label: "Anti-inflammatoire génitale et urinaire",
      value: "Anti-inflammatoire génitale et urinaire",
    },
    { label: "Insectifuge", value: "Insectifuge" },
    { label: "Stimulante apéritive", value: "Stimulante apéritive" },
    { label: "Équilibrante immunitaire", value: "Équilibrante immunitaire" },
    { label: "Fatigue", value: "Fatigue" },
    { label: "Purificatrice rénale", value: "Purificatrice rénale" },
    { label: "Régulatrice hydrique", value: "Régulatrice hydrique" },
    { label: "Hémostatique", value: "Hémostatique" },
    { label: "Anti-asthmatique", value: "Anti-asthmatique" },
    {
      label: "Anti-infectieuse bronchopulmonaire",
      value: "Anti-infectieuse bronchopulmonaire",
    },
    { label: "Anti-infectieuse ORL", value: "Anti-infectieuse ORL" },
    {
      label: "Régulatrice du rythme cardiaque",
      value: "Régulatrice du rythme cardiaque",
    },
    { label: "Décongestionnante", value: "Décongestionnante" },
    { label: "Dilatatrice", value: "Dilatatrice" },
    { label: "Antimycosique", value: "Antimycosique" },
    { label: "Tonique", value: "Tonique" },
    { label: "Antiputride", value: "Antiputride" },
    { label: "Neurorégulatrice", value: "Neurorégulatrice" },
    { label: "Régulatrice lymphatique", value: "Régulatrice lymphatique" },
    { label: "Microbicide", value: "Microbicide" },
    {
      label: "Décongestionnante prostatique",
      value: "Décongestionnante prostatique",
    },
    { label: "Phlébotonique", value: "Phlébotonique" },
    { label: "Tonifiante cutanée", value: "Tonifiante cutanée" },
    { label: "Antipsoriasique", value: "Antipsoriasique" },
    { label: "Tonique musculaire", value: "Tonique musculaire" },
    { label: "Laxative douce", value: "Laxative douce" },
    { label: "Désinfectante aérienne", value: "Désinfectante aérienne" },
    { label: "Anti-douleur", value: "Anti-douleur" },
    { label: "Anaphrodisiaque", value: "Anaphrodisiaque" },
    {
      label: "Calmante du système nerveux",
      value: "Calmante du système nerveux",
    },
    { label: "Antifongique intestinale", value: "Antifongique intestinale" },
    { label: "Tonique immunitaire", value: "Tonique immunitaire" },
    { label: "Régulatrice endocrinienne", value: "Régulatrice endocrinienne" },
    { label: "Régulatrice immunitaire", value: "Régulatrice immunitaire" },
    { label: "Apaisante", value: "Apaisante" },
    {
      label: "Calmante respiratoire et cardiaque",
      value: "Calmante respiratoire et cardiaque",
    },
    { label: "Stimulante ovarienne", value: "Stimulante ovarienne" },
    { label: "Équilibrante intestinale", value: "Équilibrante intestinale" },
    { label: "Hyperémiante", value: "Hyperémiante" },
    { label: "Utérotonique", value: "Utérotonique" },
    { label: "Stomachique", value: "Stomachique" },
    { label: "Tonique utérine", value: "Tonique utérine" },
    { label: "Anti-allergique", value: "Anti-allergique" },
    { label: "Anti-infectieuse aérienne", value: "Anti-infectieuse aérienne" },
    {
      label: "Décongestionnante utéro-ovarienne",
      value: "Décongestionnante utéro-ovarienne",
    },
    { label: "Stimulante hormonale", value: "Stimulante hormonale" },
    { label: "Fébrifuge", value: "Fébrifuge" },
    { label: "Fluidifiante", value: "Fluidifiante" },
    { label: "Réchauffante musculaire", value: "Réchauffante musculaire" },
    { label: "Tonique circulatoire", value: "Tonique circulatoire" },
    { label: "Déstressante", value: "Déstressante" },
    { label: "Sédative", value: "Sédative" },
    { label: "Myorelaxante", value: "Myorelaxante" },
    { label: "Mucolytique", value: "Mucolytique" },
    {
      label: "Anti-infectieuse urinaire et génitale",
      value: "Anti-infectieuse urinaire et génitale",
    },
    { label: "Astringente", value: "Astringente" },
    { label: "Cardiotonique", value: "Cardiotonique" },
    { label: "Tonifiante", value: "Tonifiante" },
    {
      label: "Antispasmodique respiratoire",
      value: "Antispasmodique respiratoire",
    },
    { label: "Assainissante", value: "Assainissante" },
    { label: "Oxygénante", value: "Oxygénante" },
    { label: "Apéritive", value: "Apéritive" },
    { label: "Sédative puissante", value: "Sédative puissante" },
    {
      label: "Anti-inflammatoire pulmonaire",
      value: "Anti-inflammatoire pulmonaire",
    },
    { label: "Reposante", value: "Reposante" },
    { label: "Apaisante", value: "Apaisante" },
    { label: "Aphrodisiaque", value: "Aphrodisiaque" },
    { label: "Relaxante", value: "Relaxante" },
    {
      label: "Apaisante du système nerveux",
      value: "Apaisante du système nerveux",
    },
    { label: "Déstressante", value: "Déstressante" },
    { label: "Relaxante nerveuse", value: "Relaxante nerveuse" },
    { label: "Stimulante cognitive", value: "Stimulante cognitive" },
    { label: "Tonifiante", value: "Tonifiante" },
    {
      label: "Régulateur du système nerveux",
      value: "Régulateur du système nerveux",
    },
    { label: "Énergisante", value: "Énergisante" },
    { label: "Positivante", value: "Positivante" },
    { label: "Calmante", value: "Calmante" },
    { label: "Blocages psychiques", value: "Blocages psychiques" },
    { label: "Tranquillisante", value: "Tranquillisante" },
    { label: "Tonique", value: "Tonique" },
    {
      label: "Relaxante du système nerveux",
      value: "Relaxante du système nerveux",
    },
    {
      label: "Equilibrante du système nerveux",
      value: "Equilibrante du système nerveux",
    },
    { label: "Favorise le sommeil", value: "Favorise le sommeil" },
    {
      label: "Tonifiante du système nerveux",
      value: "Tonifiante du système nerveux",
    },
    {
      label: "Rafraichissante, oxygénante",
      value: "Rafraichissante, oxygénante",
    },
    { label: "Apaisante nerveuse", value: "Apaisante nerveuse" },
    { label: "Dynamisante", value: "Dynamisante" },
    { label: "Tonique et oxygénante", value: "Tonique et oxygénante" },
    { label: "Revitalisante", value: "Revitalisante" },
    {
      label: "Équilibrante sexuelle et hormonale",
      value: "Équilibrante sexuelle et hormonale",
    },
    { label: "Fortifiante", value: "Fortifiante" },
    { label: "Immuno - stimulante", value: "Immuno - stimulante" },
    { label: "Antidépressive", value: "Antidépressive" },
    { label: "Équilibrante nerveuse", value: "Équilibrante nerveuse" },
    { label: "Stimulante sexuelle", value: "Stimulante sexuelle" },
    { label: "Stimulante", value: "Stimulante" },
    { label: "Stimulant psychique", value: "Stimulant psychique" },
    { label: "Tonifiante nerveuse", value: "Tonifiante nerveuse" },
    { label: "Tonifiante psychique", value: "Tonifiante psychique" },
    { label: "Apaisante et relaxante", value: "Apaisante et relaxante" },
    { label: "Assainissante", value: "Assainissante" },
    { label: "Réconfortante", value: "Réconfortante" },
    {
      label: "Recentre les énergies vitales",
      value: "Recentre les énergies vitales",
    },
    { label: "Antidouleur", value: "Antidouleur" },
    { label: "Apaisante sur les piqûres", value: "Apaisante sur les piqûres" },
    { label: "Préparatrice du sommeil", value: "Préparatrice du sommeil" },
    { label: "Euphorisante", value: "Euphorisante" },
    { label: "Harmonisante nerveuse", value: "Harmonisante nerveuse" },
    { label: "Tonifiante du psychisme", value: "Tonifiante du psychisme" },
    { label: "Antistress", value: "Antistress" },
    { label: "Calmante psychique", value: "Calmante psychique" },
    { label: "Neurorégulatrice", value: "Neurorégulatrice" },
    { label: "Neurotonique", value: "Neurotonique" },
    { label: "Calmante nerveuse", value: "Calmante nerveuse" },
    { label: "Calmante puissante", value: "Calmante puissante" },
    { label: "Restructurante intérieure", value: "Restructurante intérieure" },
    { label: "Régulatrice neurologique", value: "Régulatrice neurologique" },
    { label: "Antioxydante", value: "Antioxydante" },
    { label: "Purifiante", value: "Purifiante" },
    { label: "Adoucissante", value: "Adoucissante" },
    { label: "Raffermissante", value: "Raffermissante" },
    { label: "Antiallergique", value: "Antiallergique" },
    { label: "Antiprurigineuse", value: "Antiprurigineuse" },
    { label: "Odorante", value: "Odorante" },
    { label: "Anti-rides", value: "Anti-rides" },
    { label: "Dépigmentaire", value: "Dépigmentaire" },
    { label: "Désclérosante", value: "Désclérosante" },
    { label: "Régénérante cutanée", value: "Régénérante cutanée" },
    { label: "Antirides", value: "Antirides" },
    { label: "Tonifiante cutanée", value: "Tonifiante cutanée" },
    { label: "Eclat du teint", value: "Eclat du teint" },
    { label: "Drainage lymphatique", value: "Drainage lymphatique" },
    { label: "Anti-cellulitique", value: "Anti-cellulitique" },
    { label: "Rafraîchissante", value: "Rafraîchissante" },
    { label: "Fortifiante capillaire", value: "Fortifiante capillaire" },
    { label: "Anti-hématome", value: "Anti-hématome" },
    { label: "Fluidifiante sanguine", value: "Fluidifiante sanguine" },
    { label: "Tonifiante tissulaire", value: "Tonifiante tissulaire" },
    { label: "Radioprotectrice cutanée", value: "Radioprotectrice cutanée" },
    {
      label: "Anti-inflammatoire cutanée",
      value: "Anti-inflammatoire cutanée",
    },
    { label: "Hydratante", value: "Hydratante" },
    { label: "Régénératrice", value: "Régénératrice" },
    {
      label: "Régulatrice de la transpiration",
      value: "Régulatrice de la transpiration",
    },
    {
      label: "Soins capillaires : cheveux gras",
      value: "Soins capillaires : cheveux gras",
    },
    { label: "Assainissante", value: "Assainissante" },
    { label: "Tonifiante", value: "Tonifiante" },
    { label: "Séborégulatrice", value: "Séborégulatrice" },
    { label: "Antiparasitaire", value: "Antiparasitaire" },
    { label: "Anti-cellulite", value: "Anti-cellulite" },
    { label: "Antipigmentaire", value: "Antipigmentaire" },
    { label: "Déodorante", value: "Déodorante" },
    { label: "Apaisante cutanée", value: "Apaisante cutanée" },
    { label: "Drainante", value: "Drainante" },
    { label: "Anti-infectieuse", value: "Anti-infectieuse" },
    { label: "Revitalisante cutanée", value: "Revitalisante cutanée" },
    { label: "Apaisante", value: "Apaisante" },
    { label: "Pousse des cheveux", value: "Pousse des cheveux" },
    { label: "Sébum", value: "Sébum" },
    { label: "Astringente cutanée", value: "Astringente cutanée" },
    {
      label: "Décongestionnante des tissus",
      value: "Décongestionnante des tissu",
    },
  ],
};
